apiVersion: apps/v1 #声明了对象的API版本，Kubernetes会去对应的包里加载库文件
kind: Deployment
metadata: # Deployment的元数据
  name: my-go-app
spec:
  replicas: 1 # ReplicaSet部分的定义
  selector:
    matchLabels:
      app: go-app
  template: # Pod 模板的定义
    metadata:
      labels:
        app: go-app
    spec: # Pod里容器相关的定义
      containers:
        - name: go-app-container
          image: go-app-img #镜像名
          imagePullPolicy: IfNotPresent #如果本地不存在则拉取仓库中的 /Never 不从仓库中拉取镜像，只用本机的
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000